version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - migrate
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
    volumes:
      - .:/app
    command: ["bun", "run", "dev"]
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  migrate:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
    volumes:
      - .:/app
    entrypoint: >
      sh -c "
      bun install &&
      bun run drizzle:generate &&
      bun run drizzle:migrate
      "
    networks:
      - app-network
    command: []

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
